services:
  portainer:
    ports:
      - "9000:9000"

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL:-email@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${DEFAULT_PASSWORD:-password}
    ports:
      - "9001:80"

  keycloak:
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sql.keycloak/keycloak
      KC_DB_USERNAME: ${DEFAULT_USER:-user}
      KC_DB_PASSWORD: ${DEFAULT_PASSWORD:-password}
      KEYCLOAK_ADMIN: ${DEFAULT_USER:-user}
      KEYCLOAK_ADMIN_PASSWORD: ${DEFAULT_PASSWORD:-password}
    volumes:
      - ./scripts/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 9002:8080

  sql.keycloak:
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DEFAULT_USER:-user}
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD:-password}
    ports:
      - 9003:5432

  sql.recruiter:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DEFAULT_USER:-user}
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD:-password}
    ports:
      - 9004:5432

  #questions.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Development}
  #    - ConnectionStrings:Questions=Username=${DEFAULT_USER};Password=${DEFAULT_PASSWORD};Server=sql.recruiter;Database=questions;
  #    - Keycloak__Authority=http://host.docker.internal:9002
  #    - Keycloak__Realm=recruiter
  #    - Keycloak__ClientId=recruiter
  #    - Keycloak__ClientSecret=Lzn5DMaTgnZvrIZpUiXYcVCHTRToBtNR
  #  ports:
  #    - 9005:8080

  #webapp:
  #  environment:
  #    - NEXT_PUBLIC_AUTH_ISSUER=http://host.docker.internal:9002/realms/recruiter
  #    - NEXT_PUBLIC_AUTH_CLIENT_ID=recruiter
  #    - NEXT_PUBLIC_AUTH_CLIENT_SECRET=Lzn5DMaTgnZvrIZpUiXYcVCHTRToBtNR
  #    - NEXT_PUBLIC_AUTH_SCOPE=openid profile email
  #    - NEXT_PUBLIC_API_URL=http://host.docker.internal:9005
  #    - NEXT_PUBLIC_AUTH_URL=http://host.docker.internal:3000
  #  ports:
  #    - 9006:3000
