networks:
  nat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 178.80.0.0/16

services:
  webapp:
    ports:
      - 3000:3000
    networks:
      nat:
        ipv4_address: 178.80.0.2
